# Generated by Django 4.1.2 on 2023-04-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
