# Generated by Django 4.1.2 on 2023-04-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='acctUsername',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
