# Generated by Django 4.1.2 on 2023-04-07 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_account_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
