# Generated by Django 4.1.2 on 2023-04-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='acctUsername',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.account'),
        ),
    ]
