# Generated by Django 4.1.2 on 2023-04-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='acctUsername',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amt_Ephemeral_Volume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amt_Memory',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amt_Volume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='amt_vCPU',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
